import { OpaqueToken } from '@angular/core';

export const lookupListToken = new OpaqueToken('lookupListToken');

export const lookupLists = {
  gender: ['Male', 'Female'],
  marital: ['Single','Married'],
  status: ['Contract', 'Permanent'],
  nationality: [
    'Americans',
    'Australians',
    'Austrians',
    'Brazilians',
    'British',
    'Cambodians',
    'Cameroonians',
    'Canadians',
    'Chinese',
    'Czechs',
    'Dutch',
    'English',
    'Eritreans',
    'Filipinos',
    'French',
    'Germans',
    'Greeks',
    'Hondurans',
    'Hong Kong',
    'Hungarians',
    'Icelanders',
    'Indonesians',
    'Japanese',
    'Koreans',
    'Libyans',
    'Malaysians',
    'Moldovans',
    'Moroccans',
    'Nigerians',
    'Norwegians',
    'Pakistanis',
    'Portuguese',
    'Russians',
    'Saudis',
    'Singaporeans',
    'Swiss',
    'Syrians',
    'Thais',
    'Turks'
  ],
  grade: ['SE-JP','SE-PG','SE-AP','SE-AN'],
};